// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LAB1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void lAB1() {
    driver.get("https://www.google.com/search?q=Testing+Method&sca_esv=02b043e6cf9f2f2b&sxsrf=APpeQnvdZoiWUGYshKGAT0Y8qwQZ86F1rQ%3A1785734597420&source=hp&ei=xSVwavyeF7CjnesP-MDPuAY&iflsig=ABILxe8AAAAAanAz1SFZDSoBwchD3TD91d48QwK09ft2&ved=0ahUKEwi8ldzi24OWAxWwUWcHHXjgE2cQ4dUDCCs&uact=5&oq=Testing+Method&gs_lp=Egdnd3Mtd2l6Ig5UZXN0aW5nIE1ldGhvZDIEECMYJzIFEAAYgAQyChAAGIAEGBQYhwIyBRAAGIAEMgoQABiABBgUGIcCMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARI1whQAFgAcAB4AJABAJgBc6ABc6oBAzAuMbgBA8gBAPgBAvgBAZgCAaACgAGYAwCSBwMwLjGgB_UGsgcDMC4xuAeAAcIHAzMtMcgHCYAIAQ&sclient=gws-wiz");
    driver.manage().window().setSize(new Dimension(1068, 816));
    {
      WebElement element = driver.findElement(By.cssSelector(".XVwoZ"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".in7vHe > .niO4u")).click();
    js.executeScript("window.scrollTo(0,196.8000030517578)");
    {
      WebElement element = driver.findElement(By.cssSelector(".gb_9a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
